### PR TITLE
Add usage to readme

### PR DESCRIPTION
**Pull request by niels-numbers**
It wasn't mentioned anywhere what the namespace of the class is. I had to go to the vendor and find out its loaded by classmap. I think it should be mentioned in the readme how to access the class.

### CODE REVIEW

**Comment by JanSlabon** [comment]
But the class-name isn't an _alias_ but it's the class-name as of the original class which is not name-spaced at all. So IMHO it would only make sense to simply give a simple usage example but do not call anything an alias which isn't an alias :-)

So mabye this should be enough:

    ## Usage
    Notice that tFPDF is not name-spaced. You can create an instance this way:

    ```php 
        $pdf = new \tFPDF();
        ...
    ```
?

**Comment by niels-numbers** [comment]
You right, I won't call it alias again and updated the PR accordingly.

**Comment by JanSlabon** [comment]
Are you fine with my change? If so I would merge this, thanks!

**Comment by niels-numbers** [comment]
Yes! :)

Thank you

**Comment by JanSlabon** [comment]
hehe, ok, for sure the namespace needs to be defined separately and not in the classname itself, my fault.

**Pull request merged**
